
CREATE TABLE weather_data
(
lon float,
    lat float,
    weather_id VARCHAR (100),
    weather_main VARCHAR (100),
    weather_icon VARCHAR (100),
    weather_description VARCHAR (100),
    weather_base VARCHAR (100),
    temp float,
    feels_like float,
    temp_min float,
    temp_max float,
    pressure int,
    humidity int,
    sea_level int,
    grnd_level int,
    visibility int,
    wind_speed float,
    wind_deg int,
    wind_gust float,
    cloud_all int,
    dt int,
    sys_tire int,
    sys_id int,
    sys_country VARCHAR (100),
    sys_sunrise int,
    sys_sunset int,
    timezone int,
    id int,
    name VARCHAR (100),
    cod int
)